db:
  # connection:
  host: 'localhost'
  port: 5432
  username: postgres
  password: 'password123'
  synchronize: true

jwt:
  secret: 'topsecret51'
# postgresql://KyuubiTila:UiZW1FpmXa5Y@ep-cool-mouse-77570802.us-east-2.aws.neon.tech/neondb?sslmode=require
